DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS urgency CASCADE;

create table task
(
   task_id integer generated by default as identity,
   difficulty varchar (255) not null,
   length varchar (255) not null,
   name varchar (255) not null,
   description varchar (255) not null,
   fk_urgency_id integer,
   primary key (task_id)
);

create table urgency
(
   urgency_id integer generated by default as identity,
   name varchar (255),
   primary key (urgency_id)
);

